name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 1.0.0
homepage: https://github.com/hivedb/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  build: ^2.5.4
  source_gen: ^1.4.0
  hive:
    git:
      url: https://github.com/ExploreLtd/hive.git
      ref: main
  analyzer: ">=4.6.0 <7.0.0"
  dartx: ^1.2.0
  source_helper: ^1.3.3
dev_dependencies:
  test: ^1.26.3
  build_test: any
  build_runner: any
  pedantic: ^1.11.1